export default {
    overview1: "This is the law firm you have been looking for, with first rate service and affordable rates, Inkhorn is the future of litigation in San Diego. As an upstart San Diego business law firm, we specialize as litigators and trial lawyers and are working towards offering full-service legal advice to our clients.",
    overview2: "Every member of our staff signs a pledge to uphold the highest standard of ethics and morality, and the principles or our practice are time-honored traditions of honesty, integrity, transparency, diligence and focus. We believe that by serving our clients, we are serving God.",
    litigation: "We begin with a trial-ready approach and willingness handle any matter before any Court in the State of California. From this position, we work to resolve disputes long before they reach trial. With the best team in San Diego, and",
    civilRights: "If one person in our county suffers a violation of their civil rights, then we all suffer with them. It is our goal to make sure every private or public action that would affect the rights of our clients is vigorously opposed. We use every tool at our disposal to vindicate the rights of our clients, including the Unruh Civil Rights Act, the Tom Bane Act, the Ralph Civil Rights Act, the Constitution of the State of California, and the Constitution of the United States of America.",
    huamnTrafficking: "California Civil Code § 52.5(a) states that “A victim of human trafficking, as defined in Section 236.1 of the Penal Code, may bring a civil action for actual damages, compensatory damages, punitive damages, injunctive relief, any combination of those, or any other appropriate relief. A prevailing plaintiff may also be awarded attorney’s fees and costs.” We are dedicated to seeing Human Trafficking ended in Southern California. We uphold the highest standards of privacy for our clients, and are willing to bring a civil suit against any predator in our community.",
    transactionalPractice: "Our firm is ready to help in any kind of transaction, from business formation to complex contracts and information on employment law - we will take the time to make sure our clients get it right the first time and avoid costly litigation down the road.",
    causes1: "Our business is purposed to serve our community. We believe in physical, mental and spiritual health for every individual in our county, beginning with children.",
    causes2: "We strive to have the same testimony as Job did when he said “I rescued the poor who cried for help, and the fatherless who had none to assist them. The one who was dying blessed me; I made the widow’s’ heart sing. I put on righteousness as my clothing; justice was my robe and my turban. I was eyes to the blind and feet to the lame. I was a father to the needy; I took up the case of the stranger. I broke the fangs of the wicked and snatched the victims from their teeth.” (Job 29:12-17).",
    causes3: "We donate to Abiding Place Ministries, the San Diego Youth Development Center, and We Love Orphans because of their work with the poor, needy and fatherless children here in San Diego and abroad."

}